name: Publish on GitHub Pages

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - id: sitepackages
        run: echo "path=$(python -c 'import site; print(site.getsitepackages()[0])')" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - name: Arrange Reveal.js plugin
        run: ./prepare_copycode.sh ${{ steps.sitepackages.outputs.path }}/sphinx_revealjs/themes/sphinx_revealjs/static/revealjs4/plugin/
      - name: Build slide
        run: |
          make revealjs
          rm -r build/revealjs/_sources
      - name: Publish on GitHub Pages
        uses: ftnext/action-push-ghpages@v1.0.0
        with:
          build_dir: build/revealjs
          github_token: ${{ secrets.GITHUB_TOKEN }}
